language: r
cache: packages
services:
  - docker
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
addons:
  apt:
    packages:
      - python3-pip
before_script:
  - pip3 install orderly-web
  - orderly-web start inst/config
